# Generated by Django 4.2 on 2023-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamers', '0003_rename_evolutionforms_evolutionform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
